// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package service

import (
	"context"

	"github.com/scality/nodeip-discovery/pkg/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockInterfaceLister creates a new instance of MockInterfaceLister. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockInterfaceLister(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockInterfaceLister {
	mock := &MockInterfaceLister{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockInterfaceLister is an autogenerated mock type for the InterfaceLister type
type MockInterfaceLister struct {
	mock.Mock
}

type MockInterfaceLister_Expecter struct {
	mock *mock.Mock
}

func (_m *MockInterfaceLister) EXPECT() *MockInterfaceLister_Expecter {
	return &MockInterfaceLister_Expecter{mock: &_m.Mock}
}

// ListInterfaces provides a mock function for the type MockInterfaceLister
func (_mock *MockInterfaceLister) ListInterfaces() ([]domain.IfaceAddrs, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ListInterfaces")
	}

	var r0 []domain.IfaceAddrs
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]domain.IfaceAddrs, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []domain.IfaceAddrs); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.IfaceAddrs)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockInterfaceLister_ListInterfaces_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListInterfaces'
type MockInterfaceLister_ListInterfaces_Call struct {
	*mock.Call
}

// ListInterfaces is a helper method to define mock.On call
func (_e *MockInterfaceLister_Expecter) ListInterfaces() *MockInterfaceLister_ListInterfaces_Call {
	return &MockInterfaceLister_ListInterfaces_Call{Call: _e.mock.On("ListInterfaces")}
}

func (_c *MockInterfaceLister_ListInterfaces_Call) Run(run func()) *MockInterfaceLister_ListInterfaces_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockInterfaceLister_ListInterfaces_Call) Return(ifaceAddrss []domain.IfaceAddrs, err error) *MockInterfaceLister_ListInterfaces_Call {
	_c.Call.Return(ifaceAddrss, err)
	return _c
}

func (_c *MockInterfaceLister_ListInterfaces_Call) RunAndReturn(run func() ([]domain.IfaceAddrs, error)) *MockInterfaceLister_ListInterfaces_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIPExtracter creates a new instance of MockIPExtracter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIPExtracter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIPExtracter {
	mock := &MockIPExtracter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIPExtracter is an autogenerated mock type for the IPExtracter type
type MockIPExtracter struct {
	mock.Mock
}

type MockIPExtracter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIPExtracter) EXPECT() *MockIPExtracter_Expecter {
	return &MockIPExtracter_Expecter{mock: &_m.Mock}
}

// ExtractIPs provides a mock function for the type MockIPExtracter
func (_mock *MockIPExtracter) ExtractIPs(ifaces []domain.IfaceAddrs) string {
	ret := _mock.Called(ifaces)

	if len(ret) == 0 {
		panic("no return value specified for ExtractIPs")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func([]domain.IfaceAddrs) string); ok {
		r0 = returnFunc(ifaces)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockIPExtracter_ExtractIPs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExtractIPs'
type MockIPExtracter_ExtractIPs_Call struct {
	*mock.Call
}

// ExtractIPs is a helper method to define mock.On call
//   - ifaces []domain.IfaceAddrs
func (_e *MockIPExtracter_Expecter) ExtractIPs(ifaces interface{}) *MockIPExtracter_ExtractIPs_Call {
	return &MockIPExtracter_ExtractIPs_Call{Call: _e.mock.On("ExtractIPs", ifaces)}
}

func (_c *MockIPExtracter_ExtractIPs_Call) Run(run func(ifaces []domain.IfaceAddrs)) *MockIPExtracter_ExtractIPs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []domain.IfaceAddrs
		if args[0] != nil {
			arg0 = args[0].([]domain.IfaceAddrs)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIPExtracter_ExtractIPs_Call) Return(s string) *MockIPExtracter_ExtractIPs_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockIPExtracter_ExtractIPs_Call) RunAndReturn(run func(ifaces []domain.IfaceAddrs) string) *MockIPExtracter_ExtractIPs_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockNodeAnnotater creates a new instance of MockNodeAnnotater. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockNodeAnnotater(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockNodeAnnotater {
	mock := &MockNodeAnnotater{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockNodeAnnotater is an autogenerated mock type for the NodeAnnotater type
type MockNodeAnnotater struct {
	mock.Mock
}

type MockNodeAnnotater_Expecter struct {
	mock *mock.Mock
}

func (_m *MockNodeAnnotater) EXPECT() *MockNodeAnnotater_Expecter {
	return &MockNodeAnnotater_Expecter{mock: &_m.Mock}
}

// AnnotateNode provides a mock function for the type MockNodeAnnotater
func (_mock *MockNodeAnnotater) AnnotateNode(ctx context.Context, formattedIPs string) error {
	ret := _mock.Called(ctx, formattedIPs)

	if len(ret) == 0 {
		panic("no return value specified for AnnotateNode")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, formattedIPs)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockNodeAnnotater_AnnotateNode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AnnotateNode'
type MockNodeAnnotater_AnnotateNode_Call struct {
	*mock.Call
}

// AnnotateNode is a helper method to define mock.On call
//   - ctx context.Context
//   - formattedIPs string
func (_e *MockNodeAnnotater_Expecter) AnnotateNode(ctx interface{}, formattedIPs interface{}) *MockNodeAnnotater_AnnotateNode_Call {
	return &MockNodeAnnotater_AnnotateNode_Call{Call: _e.mock.On("AnnotateNode", ctx, formattedIPs)}
}

func (_c *MockNodeAnnotater_AnnotateNode_Call) Run(run func(ctx context.Context, formattedIPs string)) *MockNodeAnnotater_AnnotateNode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockNodeAnnotater_AnnotateNode_Call) Return(err error) *MockNodeAnnotater_AnnotateNode_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockNodeAnnotater_AnnotateNode_Call) RunAndReturn(run func(ctx context.Context, formattedIPs string) error) *MockNodeAnnotater_AnnotateNode_Call {
	_c.Call.Return(run)
	return _c
}
